### ISSUE TITLE
i want to disable dropdown how can i ? i use snackbar to show error

### ISSUE THREAD

**Issue by pradhyumansinh9849** [WrathChaos/react-native-internet-connection-alert#10]

**Comment by kuraydev** [comment]
Hello,
You cannot do it with this library, this library already provides a built-in dropdown solution. You can create your own with snackbar.

You can check this out:
https://github.com/WrathChaos/react-native-internet-connection-alert/blob/405d6858175bf1cd8449ffd3a2cbb4dd14040d2f/lib/InternetConnectionAlert.tsx#L34
