### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by avspera** [WrathChaos/react-native-internet-connection-alert#2]
I'm getting this error while trying to install with the command `npm i react-native-internet-connection-alert`

`Invalid tag name "=> 5.9.6": Tags may not have any characters that encodeURIComponent encodes`

i've already installed dependencies. What is going on here?

**Comment by kuraydev** [comment]
Let me check

**Comment by kuraydev** [comment]
hello @avspera,
I've updated the example with an empty project initialization and I could not reproduce this problem.

Can you try to install it within an empty project? and please check the example. 

If you can share a minimal reproducible example with me, I can help you with it.

**Comment by avspera** [comment]
thank you, i'll try with an empty project and let you known!

**Comment by kuraydev** [comment]
Waiting for your feedback :)

**Comment by ballbrk** [comment]
Hi I've installed npm version 7.6.1 . This is the result when try to install your package
npm i react-native-internet-connection-alert
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "=> 5.9.6": Tags may not have any characters that encodeURIComponent encodes.

**Comment by kuraydev** [comment]
Hello @ballbrk 
0.1.6 version is alive, can you try with that?

**Comment by kuraydev** [comment]
Version 0.1.7 is alive. 

Big thanks to @mohzameer
