### ISSUE TITLE
Dropdown alert doesn't show on android 'RELEASE' version

### ISSUE THREAD

**Issue by erez-unitronics** [WrathChaos/react-native-internet-connection-alert#6]
Hi,
I tried to use this package on release apk version of my app and it doesn't work.
Am I missing something?

Thanks

**Comment by kuraydev** [comment]
Hello @erez-unitronics,
Could you solve it? Do you still need help?

**Comment by erez-unitronics** [comment]
@WrathChaos

I solved it.
For some reason android bundle was not updated after installing the Netinfo package which is one of the dependencies for this package.

This command fixed it:

react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/

Thanks for the help!
