### ISSUE TITLE
not showing on connected but internet not reachable

### ISSUE THREAD

**Issue by amalmohann** [WrathChaos/react-native-internet-connection-alert#8]
this library only shows the Notification when isConnected of netinfo library is false. This has to consider the isInternetReachable attribute as well.

**Comment by kuraydev** [comment]
Hello @amalmohann 

You are right! I can add the feature as an optional. 

Of course, PR's are welcome :)

**Comment by kuraydev** [comment]
[Version 0.1.9](https://github.com/WrathChaos/react-native-internet-connection-alert/releases/tag/0.1.9)

Published :)
